### ISSUE TITLE
Get reference/location of Subscription

### ISSUE THREAD

**Issue by thSoft** [ThomasWeiser/elmfire#2]
It would be great of there was a function that given a Subscription returns the reference/location it points to.

**Comment by ThomasWeiser** [comment]
Ok, this would be possible, but it would necessitate to keep the subscriptions table (on the Javascript side) forever. Unsubscribed entries could not be deleted because otherwise the proposed function to map a `Subscription` to a `Reference` wouldn't be pure.

Do you have a certain use case in mind?

**Comment by ThomasWeiser** [comment]
Thinking a bit more about a possible implementation of such such a function: The mentioned problem about keeping old data around could be handled.

Nevertheless, I don't see the need of such a function, so I close this issue. If a good use is emerging I will reopen it.
